force-app/main/default/objects/client__c/client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Client ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/client__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last_Name</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/client__c/fields/Phone_number__c.field-meta.xml
<CustomField>
    <fullName>Phone_number__c</fullName>
    <label>Phone_number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/NameValidationHelper.cls
public class NameValidationHelper {
    Public static void TestNameValidationHandler(list<client__c>csList){
        for(client__c c:csList){
            if(c.First_Name__c=='test'){
                c.First_Name__c.addError('test is not valid name');
            }
        }
    }
       Public static void duplicateName(list<client__c>csListNew){
        for(client__c c:csListNew){
    list<client__c>cslist=[select id from client__c where First_Name__c =:c.First_Name__c and Last_Name__c=:c.Last_Name__c];
    if(cslist.size()>0){
        c.Phone_number__c.addError('duplicate Name found');
    }
}
}
   Public static void duplicateContact(list<client__c>csListNew){
        for(client__c c:csListNew){
    list<client__c>cslist=[select id from client__c where Phone_number__c=:c.Phone_number__c]; 
    if(cslist.size()>0){
        c.Phone_number__c.addError('duplicate Contact found');
    } 
        }
   }
        }