force-app/main/default/objects/client__c/client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Client ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/client__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last_Name</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UniqueNameHelper.cls
public class UniqueNameHelper {
    Public static void uniquenameHandler(list<client__c>csList){
        for(client__c c:csList){
            list<client__c>csListNew=[select id from client__c where First_Name__c=:c.First_Name__c and
                                      Last_Name__c=:c.Last_Name__c];
            if(csListNew.size()==1){
                c.addError('unique Name Found');
            }
        }
    }
}