force-app/main/default/objects/client__c/client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Client ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/client__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last_Name</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/client_backup__c/client_backup__c.object-meta.xml
<CustomObject>
    <label>client_backup</label>
    <nameField>
        <label>client_backup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>clients_backup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/client_backup__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First_Name</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/client_backup__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last_Name</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ClientBackupHelper.cls
public class ClientBackupHelper {
    public static void backupHandler(list<client__c>csList){
       
list<client_backup__c>bkList=new list<client_backup__c>();
    for(client__c c:csList){
        client_backup__c bk=new client_backup__c();
        bk.First_Name__c=c.First_Name__c;
         bk.Last_Name__c=c.Last_Name__c;      //client-no.of records-list 
        bkList.add(bk);
    }
    insert bkList;
}
}