force-app/main/default/objects/client__c/client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Client ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/client__c/fields/Count_Of_Address__c.field-meta.xml
<CustomField>
    <fullName>Count_Of_Address__c</fullName>
    <label>Count_Of_Address</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/client__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last_Name</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/client__c/fields/Recent_City__c.field-meta.xml
<CustomField>
    <fullName>Recent_City__c</fullName>
    <label>Recent_City</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdateValidationHelper.cls
public class UpdateValidationHelper {
    public static void updateValidationHandler(List<client__c>csListNew){
        for(client__c c:csListNew){
    list<client__c>csList=[select id from client__c where First_Name__c =:c.First_Name__c and Last_Name__c=:c.Last_Name__c
                          and Recent_City__c=:c.Recent_City__c  and Count_Of_Address__c=:c.Count_Of_Address__c];
    if(csList.size()>0){
        c.addError('duplicate Name found');
    }
}
}
}